### ISSUE TITLE
Analyse arbejde

### ISSUE THREAD

**Issue by toften05** [mikkwin/Bachelor#23]
Funktionelle og ikke funktionelle krav før og efter testing og interview
Evt. Andet analyse

**Comment by mikkwin** [comment]
Planer for denne opgave:

- [ ] Identificer GE's problem (Problem statement)
- [ ] Lav sub spørgsmål
- [ ] Lav Tekniker Persona
- [ ] Ud fra Persona og Empathy wall, lav krav.
